# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

install:
  - pip install git+https://github.com/hover2pi/sedkit#egg=sedkit
  - pip install -r requirements_dev.txt
  - pip install pytest pytest-cov coveralls

# command to run tests, e.g. python setup.py test
script:
  - python -m pytest tests/