name: locals
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - numpy=1.19.4
  - astropy>=4.2
  - python>=3.6.8
  - bokeh=2.2.3
  - astroquery>=0.4.2
  - scipy=1.5.3
  - pandas=1.1.5
  - pip=20.2.3
  - selenium=3.141.0
  - pytest=6.2.1
  - jupyter>=1.0.0
  - ipython>=7.12.0
  - pip:
    - svo-filters==0.3.0
    - dustmaps==1.0.4
    - numpydoc==0.8.0
    - healpy==1.14.0