name: locals
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - astropy=4.0
  - healpy=1.11.0
  - bokeh=1.3.4
  - click=7.0
  - ipython=7.12.0
  - jupyter=1.0.0
  - numpy=1.18.1
  - pytest=5.4.3
  - python=3.6.8
  - scipy=1.2.1
  - pip:
    - astroquery=0.4.1
    - numpydoc==0.8.0
    - sedkit==1.0.4
    - svo-filters==0.2.19
    - werkzeug==0.16.1
