name: locals
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - astropy=4.1
  - healpy=1.11.0
  - bokeh=2.2.3
  - click=7.0
  - ipython=7.12.0
  - jupyter=1.0.0
  - numpy=1.19.4
  - pytest=5.4.3
  - python=3.6.8
  - scipy=1.2.1
  - pip:
    - astroquery==0.4.1
    - numpydoc==0.8.0
    - sedkit==1.0.6
    - svo-filters==0.3.0
    - werkzeug==0.16.1
    - configobj==5.0.6
    - jwst==0.17.1
